env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: pure-cli
    main: ./
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.builtBy=goreleaser
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  use: github
  sort: asc
archives:
  - id: pure-cli
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
      files:
        - README.md
        - LICENSE
